* OSUI

** Experiment with Flask 

This branch is used to converting the codebase from PHP to Python with the 
Flask Framework just to see....mmm....



** Dependencies: 
*** Possibility?
- Budgie Desktop Environment

** Official Dependencies

- python-pip
	- flask
	- opencv-python
	- sh
	- mediapipe
	- SpeechRecognition
	- python-xlib


** Installation

For the python dependencies, here are the list of dependencies that
are needed for the installation of the OSUI Desktop Environment

- ~pip install flask~

- ~pip install opencv-python~

- ~pip install sh~

- ~pip install mediapipe~

- ~pip install SpeechRecognition~

- ~pip install python-xlib~

  
However, if you want it to make it faster, it is recommended to run
the ~dependencies-install.sh~ script

#+BEGIN_SRC shell
sh dependencies-install.sh
#+END_SRC




** What's in the backend?

*** Adjusting Sound Volume
For adjusting the volume in the status bar, it uses PulseAudio ~pactl~


**** Decreasing Sound Volume

#+BEGIN_SRC shell
pactl set-sink-volume @DEFAULT_SINK@ -10%
#+END_SRC


**** Increasing Sound Volume

#+BEGIN_SRC shell
pactl set-sink-volume @DEFAULT_SINK@ +10%
#+END_SRC



** What's in the src folder? 

*** Hardware Control
Scripts that are used in the backend, allowing the ability to fully
control the hardware via the OSUI Interface.


**** Inside Hardware Control

Inside the hardware control, here are the list of script Components
and description of what each of them does. 




#+BEGIN_SRC txt
Hardware Control
{
        display-brightness-control {
                display_brightness_rocker_down.sh
                display_brightness_rocker_up.sh
        }

        volume-control {
                volume_rocker_down.sh
                volume_rocker_up.sh
                volume_rocker_mute.sh
        }
}
#+END_SRC