## install--smith-pad-os-packages.sh

## This script allows the ability to install required packages on
## Smith-Pad-OS

sudo pacman -Syyu --noconfirm                                                   ## Make sure all packages are completely updated
sudo pacman -S xorg-xinit --noconfirm                                           
sudo pacman -S xorg-server --noconfirm
sudo pacman -S xorg-xinit --noconfirm
sudo pacman -S xorg-xrandr --noconfirm
sudo pacman -S xorg-xsetroot --noconfirm
sudo pacman -S xorg-xset --noconfirm
sudo pacman -S xorg-xrdb --noconfirm
sudo pacman -S xorg-xprop --noconfirm
sudo pacman -S xorg-xev --noconfirm
sudo pacman -S xorg-xinput --noconfirm
sudo pacman -S xorg-xkill --noconfirm
sudo pacman -S xorg-xlsclients --noconfirm
sudo pacman -S xorg-xlsatoms --noconfirm
sudo pacman -S xorg-xlsfonts --noconfirm
sudo pacman -S xorg-xmessage --noconfirm
sudo pacman -S xorg-xrefresh --noconfirm
sudo pacman -S xorg-xvinfo --noconfirm
sudo pacman -S xorg-xwininfo --noconfirm
sudo pacman -S xorg-xwud --noconfirm
sudo pacman -S xorg-xgamma --noconfirm
sudo pacman -S  xorg-xhost --noconfirm
sudo pacman -S xorg-xauth --noconfirm
sudo pacman -S xorg-xclipboard --noconfirm
sudo pacman -S xorg-xcursorgen --noconfirm
sudo pacman -S xorg-xdpyinfo --noconfirm
sudo pacman -S xorg-xdriinfo --noconfirm
sudo pacman -S xorg-xedit --noconfirm
sudo pacman -S xorg-xeyes --noconfirm
sudo pacman -S xorg-xfontsel --noconfirm
sudo pacman -S xorg-xfs --noconfirm
sudo pacman -S xorg-xfsinfo --noconfirm
sudo pacman -S xorg-xgc --noconfirm
sudo pacman -S xorg-xkbevd --noconfirm
sudo pacman -S xorg-xkbutils --noconfirm
sudo pacman -S xorg-xkill --noconfirm
sudo pacman -S xorg-xlsatoms --noconfirm
sudo pacman -S xorg-xlsclients --noconfirm
sudo pacman -S xorg-xlsfonts --noconfirm
sudo pacman -S xorg-xmessage --noconfirm
sudo pacman -S xorg-xmodmap --noconfirm
sudo pacman -S xorg-xpr --noconfirm
sudo pacman -S xorg-xprop --noconfirm
sudo pacman -S xorg-xrandr --noconfirm
sudo pacman -S xorg-xrdb --noconfirm
sudo pacman -S xorg-xrefresh --noconfirm
sudo pacman -S xorg-xset --noconfirm
sudo pacman -S xorg-xsetroot --noconfirm
sudo pacman -S xorg-xsm --noconfirm
sudo pacman -S xorg-xterm --noconfirm
sudo pacman -S xorg-xwd --noconfirm
sudo pacman -S xorg-xwininfo --noconfirm
sudo pacman -S xorg-xwud --noconfirm
sudo pacman -S chromium --noconfirm
sudo pacman -S sddm --noconfirm
sudo pacman -S sddm-kcm --noconfirm
sudo pacman -S kde-gtk-config --noconfirm
sudo pacmam -S kdeplasma-addons --noconfirm
sudo pacman -S kscreen --noconfirm
sudo pacman -S kwin --noconfirm
sudo pacman -S powerdevil --noconfirm
sudo pacman -S systemsettings --noconfirm
sudo pacman -S python-pip --noconfirm
sudo pacman -S python-flask --noconfirm
sudo pacman -S php --noconfirm
sudo pacman -S playerctl --noconfirm
sudo pacman -S electron --noconfirm