name: "Auto-Release"
# Documentation found here:
# https://github.com/marketplace/actions/automatic-releases

on:
  push:
    branches:
      - "main"

jobs:
  Auto-Release:
    name: "Auto-Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Changes:"
          files: |
            LICENSE.txt
            *.jar
